### ISSUE TITLE
Release v0.27.0 (please TEST!)

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#10930]
## Testing for regressions

Debug APK (built by our CI in https://github.com/TeamNewPipe/NewPipe/pull/10929): [NewPipe_v0.27.0_RC4_debug.zip](https://github.com/TeamNewPipe/NewPipe/files/15047944/NewPipe_v0.27.0_RC4_debug.zip)
Release APK (built and signed by @Stypox): [NewPipe_v0.27.0_RC4_release.zip](https://github.com/TeamNewPipe/NewPipe/files/15047940/NewPipe_v0.27.0_RC4_release.zip)

Please report **only regressions** (i.e. new issues) here, not issues that were already present in previous releases

## TODO

- [ ] Merge weblate
- [ ] Merge preferences fix
- [x] https://github.com/TeamNewPipe/NewPipeExtractor/pull/1163
- [x] #10957
- [x] #10959
- [x] #10952
- [x] https://github.com/TeamNewPipe/NewPipeExtractor/pull/1168
- [ ] https://github.com/TeamNewPipe/NewPipeExtractor/pull/1170

## NewPipeExtractor version

This version of NewPipe will ship with NewPipeExtractor version 0.23.2 (yet to be released)

<details><summary><h2>App changelog </h2></summary><p>

### New
- Add support for comment replies #10018 
- Add playlist description to playlist fragment #10091 
- Add option to reset settings #9236 
- Show overall duration of items in a playlist #6045 
- Allow ordering bookmarked playlists #8221 

### Improved
- [Android 13+] Restore support of custom notification actions #10712
  :warning: The first three notification actions (play/pause, previous and next) cannot be customized anymore on these Android versions, as they are set by the system
- Allow playing/pausing from the notification when the player is buffering #10712
- Added "free memory" check before downloading [Android N / API 24+] #10505 #10896
- Change the landscape layout of list card item #9975 
- Ask for consent before checking for updates #10790 
- Moved player notification setting to notification section #9580 

### Fixed
- Don't write defaultFormat setting, use default value #10732 
- Calculate cache key based on info type instead of item type #10717 
- Fix not considering nullability when comparing getAudioTrackType #10909 
- Trim search string and remove duplicate records from the database #8242 
- Various download fixes #10912 

### Localization and Documentation
- Update translations #10890 
- Use GitHub markdown to emphasise warning in Readme #10724 

### Development
- Update some AndroidX libraries and `compileSdk` to 34 #10086
- Update miscellaneous libraries #10530
- Update Matrix chat URL to new link #10795
- Update jsoup to 1.17.2 #10817
- Update GitHub action dependencies in workflows #10740
- Fix typo in TextLinkifier.java #10889 
- Improve app signature check #10618 
- Update workflows to use Node 20 #10908 
- BaseDescriptionFragment: Assert member is initialized #10781 
</details>

<details><summary><h2>Extractor changelog </h2></summary><p>

### New
- [YouTube] Implement emergency meta info TeamNewPipe/NewPipeExtractor#1135 
- [YouTube] Add Releases channel tab as an extractor albums channel tab TeamNewPipe/NewPipeExtractor#1147 
- [PeerTube] Add support for v6 features (frames and segments) TeamNewPipe/NewPipeExtractor#1142 

### Improved
- [YouTube] Detect new account termination messages for YouTube TeamNewPipe/NewPipeExtractor#1160
- Make `getCommentText` return `@Nonnull` values TeamNewPipe/NewPipeExtractor#1162 

### Fixed
- [PeerTube] Fix local kiosk TeamNewPipe/NewPipeExtractor#1144 
- [PeerTube] Do not accept non-URLs TeamNewPipe/NewPipeExtractor#1143 
- [MediaCCC] Allow obtaining channel tab link handler TeamNewPipe/NewPipeExtractor#1148 

### Development
- Bump org.jsoup:jsoup from 1.16.2 to 1.17.2 TeamNewPipe/NewPipeExtractor#1145 
- Bump com.github.spotbugs:spotbugs-annotations from 4.8.0 to 4.8.3 TeamNewPipe/NewPipeExtractor#1138 
- Bump actions/setup-java from 3 to 4 TeamNewPipe/NewPipeExtractor#1132 
- Bump org.junit:junit-bom from 5.10.0 to 5.10.2 TeamNewPipe/NewPipeExtractor#1156 
- Bump actions/cache from 3 to 4 TeamNewPipe/NewPipeExtractor#1153 
- Bump actions/upload-artifact from 3 to 4 TeamNewPipe/NewPipeExtractor#1139 
- LocaleCompat.forLanguageTag: return Optional if parsing fails TeamNewPipe/NewPipeExtractor#1151 
</details>

**Comment by azzaire** [comment]
The 48kbps aac or lower option is gone in the download menu. Please fix it. Thx

**Comment by NewNewPipe** [comment]
I display comments under the video under whichn there are 26,000 NP displayed only about 1,000 of them.

**Comment by lofcz** [comment]
org.schabi.newpipe.extractor.stream.Description.getType attemps to do something on a null value which causes the app to crash. Happens unreliably when either focusing the app or attempting to play any video

**Comment by Stypox** [comment]
It's fixed on the extractor dev, but again the comments fix branch which the RC was based on is some commits behind dev

**Comment by prasetyodedy** [comment]
background play needs to be pressed 2x to work, this has been the case since 2.6.1 and before

**Comment by minecraftchest1** [comment]
I can only view one page of comments now. This was not the case in 0.26.1

**Comment by AudricV** [comment]
If that's for YouTube, that's a mistake from my side that I fixed in the extractor code. See https://github.com/TeamNewPipe/NewPipeExtractor/pull/1163#issuecomment-2038027408.

**Comment by zombiestitches** [comment]
The 'play all' button only queues the first video.

**Comment by FranciscoPombal** [comment]
Raising awareness for https://github.com/TeamNewPipe/NewPipe/issues/10746, please take a look at it for this release if possible.

I know it's possible to add NewPipe's own repo as a workaround, but that's some additional friction for less tech savvy users and it's just more convenient if it's available in the default repo.

As of writing, the latest version available on f-droid's default repo is `0.25.2`.

**Comment by AudricV** [comment]
@fenopa Please do not ping specific members for such cases.

If you get an error report generated by the app, please try to search it in the existing issues (using partially or completely the first line of the error stacktrace is a good idea and the best chance to get results) to see if it is not already known. If not, please post the error report in this issue.

**Comment by Stypox** [comment]
RC2 landed:
- fixed not loading more comments
- fixed crash when old comment layout is provided by YouTube (i.e. the NullPointerException above), since now the NewPipeExtractor is up-to-date
Release APK (built and signed by @Stypox): [NewPipe_v0.27.0_RC2_release.zip](https://github.com/TeamNewPipe/NewPipe/files/14899138/NewPipe_v0.27.0_RC2_release.zip)

**Comment by NewNewPipe** [comment]
It looks like more comments are already loaded in RC2, whether all of them I don't know yet.

Thanks for launching the functionality
in the comments section about displaying replies to comments.

**Comment by JohhanSam** [comment]
## Exception
* __User Action:__ requested feed
* __Request:__ 
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UC0vBXGSyV14uvJ4hECDOl0Q
	at org.schabi.newpipe.local.feed.service.FeedLoadManager.loadStreams(FeedLoadManager.kt:229)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager.access$loadStreams(FeedLoadManager.kt:33)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager$startLoading$7.apply(FeedLoadManager.kt:113)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager$startLoading$7.apply(FeedLoadManager.kt:112)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:116)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:132)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:399)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException
	at org.schabi.newpipe.local.feed.service.FeedUpdateInfo.<init>(FeedUpdateInfo.kt:39)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager.loadStreams(FeedLoadManager.kt:220)
	... 13 more

```
</details>
<hr>

**Comment by Stypox** [comment]
> Exception: User Action: requested feed

@JohhanSam that's not a regression (i.e. it was there even in 0.26.1, see #10863). Anyway, could you test https://github.com/TeamNewPipe/NewPipe/pull/10957?

> it's not possible to watch anything on recent releases at all for a couple of days. It always crashes. Nightly 97 is the last one working I think. 97 to 111 are all crashing at all times.

@fenopa could you provide more information on the crash you are experiencing, and open an issue for it? Since nightly 97 was the same as release 0.26.0, this is also not a regression though.

> player notification buttons don't work. android 12.

@NaN-Sz I can reproduce with RC1, but now I can't with RC2. Can you confirm that this is the case? I think Android Studio messed up the package name in `BuildConfig` since I forgot to "Sync project with Gradle files" which caused intents to refer to the wrong package name, or something like that (can't be sure though)

**Comment by AudricV** [comment]
Rotating your device outside of the app when the comment replies view was the last view shown makes the app crash. Here is a video which shows the problem:

https://github.com/TeamNewPipe/NewPipe/assets/74829229/e525b2b7-6860-47c1-9947-669d2d163973

<details>

<summary>Stacktrace captured with Scoop</summary>

```
FATAL EXCEPTION: main
Process: org.schabi.newpipe.debug.release0270, PID: 7683
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.schabi.newpipe.extractor.comments.CommentsInfoItem.getUploaderAvatars()' on a null object reference
	at org.schabi.newpipe.fragments.list.comments.CommentRepliesFragment.lambda$getListHeaderSupplier$1(CommentRepliesFragment.java:83)
	at org.schabi.newpipe.fragments.list.comments.CommentRepliesFragment.$r8$lambda$ZCpsyvbpSBAi7u7hr8uTSdFpL6M(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.comments.CommentRepliesFragment$$ExternalSyntheticLambda1.get(Unknown Source:2)
	at org.schabi.newpipe.info_list.InfoListAdapter.onCreateViewHolder(InfoListAdapter.java:291)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7788)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4485)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3786)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:938)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

</details>

Device: Google Pixel 7a running Android 14 QPR stock ROM

(The `ErrorReportActivity` doesn't open, so I don't have a generated error report.)

**Comment by B0pol** [comment]
Timestamps in comment replies are not clickable

https://www.youtube.com/watch?v=GKh2LdXNU3g

@armelolsens2496
2:10 incroyable ❤😭

It’s clickable in comment views, but if you click on replies it isn’t anymore.

I'm not sure how actual comment replies behave (i.e. replies to a comment, what i said is reply to video but in comment replies view), I couldn’t find one

**Comment by TheCRISTLAD** [comment]
im import my preferences/config, I passed all my configuration without any problem

**Comment by js290** [comment]
Are these RC builds available via the NewPipe F-Droid repo?

**Comment by JamesClarke7283** [comment]
> Are these RC builds available via the NewPipe F-Droid repo?

No, as its a tester only build. you are welcome to try it out though. Dont know when it will be released but i hope soon.

So far no issues for me.

**Comment by Stypox** [comment]
@B0pol your issue is actually already fixed after the latest merged changes in https://github.com/TeamNewPipe/NewPipeExtractor/pull/1163, we'll publish a new RC soon

**Comment by Stypox** [comment]
Here is RC3 debug (unfortunately no dev is available to build the release version at the moment, so please test this one): [NewPipe_v0.27.0_RC3_debug.zip](https://github.com/TeamNewPipe/NewPipe/files/14954405/NewPipe_v0.27.0_RC3_debug.zip)

**Comment by JohhanSam** [comment]
One question (altho technically a feature request I feel like this place is better to ask), would it be possible to add a setting that would change the behavior of the timestamp (in comments)? I primarily would like to be able to switch the popup opening off and on.

**Comment by armibotexe** [comment]
> > @fenopa could you provide more information on the crash you are experiencing, and open an issue for it? Since nightly 97 was the same as release 0.26.0, this is also not a regression though.
> 
> @Stypox not having any crashes with the NewPipe_v0.27.0_RC2_release you posted on this thread. I was trying nightly releases here: https://github.com/TeamNewPipe/NewPipe-nightly/releases and all recent ones were crashing.

@fenopa let me explain, [NewPipe-nightly](https://github.com/TeamNewPipe/NewPipe-nightly) releases are generated through GitHub actions, which is automated. It compiles the most recent commit from the [dev](https://github.com/TeamNewPipe/NewPipe/tree/dev) branch. If you look closely, you'll notice that all recent bug fixes are in a separate branch called [release-0.27.0](https://github.com/TeamNewPipe/NewPipe/tree/release-0.27.0). Once this branch marge into dev you can use NewPipe-nightly again.

**Comment by comminux** [comment]
If possible, please update NewPipe-nightly build.

**Comment by chris122380** [comment]
v0.27.0 is missing the search filter options I thought was coming in the next versions of Newpipe.

**Comment by Growebis** [comment]
My comment is probably useless but i somehow got this error code and i have no idea how to reproduce it and i didn't even notice it till later since i didn't notice anything. I will edit if i come across it again with (hopefully) steps to reproduce.
RC2 release




## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=gmEouQqDCXs
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(298, null, null, video/avc, avc1.4D4020, 2693744, null, [1280, 720, 60.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:203)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.MTK.VIDEO.DECODER.AVC
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1639)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_queueInputBuffer(Native Method)
	at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2293)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.queueInputBuffer(SynchronousMediaCodecAdapter.java:143)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1364)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:784)
	... 5 more

```
</details>
<hr>

**Comment by lnee94** [comment]
Though could a "scrool back to top" button be added for the commets

**Comment by jpggithub** [comment]
Android 11, Lineageos 18.1, Lenovo P2
Newpipe 0.27.0 RC3 works well including tree comments.
Thank you!

**Comment by stellarkookies** [comment]
Android 14, LineageOS 21, Pixel 4a 5G (bramble)
Have used 0.27.0 RC3 for about 2 weeks now. No noticeable regressions or serious issues.
Comments load properly, as well as comment trees.
Content loading is also very consistent; much better than in the current stable release.
Thanks for the good work y'all do. Looking forward to the official release ;)

**Comment by Stypox** [comment]
New RC, includes small YouTube bugfixes from https://github.com/TeamNewPipe/NewPipeExtractor/pull/1168

Release APK (built and signed by @Stypox): [NewPipe_v0.27.0_RC4_release.zip](https://github.com/TeamNewPipe/NewPipe/files/15047940/NewPipe_v0.27.0_RC4_release.zip)
<sub>Debug APK (built by our CI in https://github.com/TeamNewPipe/NewPipe/pull/10929): [NewPipe_v0.27.0_RC4_debug.zip](https://github.com/TeamNewPipe/NewPipe/files/15047944/NewPipe_v0.27.0_RC4_debug.zip)
</sub>

**Comment by millionsofplayers** [comment]
Is there an expected release date? I see rc in the name which I think means it's close (correct me if I'm wrong)

**Comment by acrodemocide** [comment]
I'm probably late to the party, but I'm pulling down the latest release and testing. I'll only report new defects (regression, not defects present in the current release -- 0.26.1) and ensure only defects that have not already been reported are documented.

**Comment by rambonette** [comment]
> Is there an expected release date? I see rc in the name which I think means it's close (correct me if I'm wrong)

The more we test, the faster will get released! Tell your firends 🎉  RC stands for "release candidate"

**Comment by somos61** [comment]
0.27.0_RC crashes trying to download with SAF turned off in settings. When SAF is on, everything is fine, but the download path in settings looks weird, like  content://com.android.externalstorage.documents/tree/primary:Download. Instead of /storage/emulated/0/Download,  when SAF is off, but crashes.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
	at org.schabi.newpipe.streams.io.StoredDirectoryHelper.getFreeMemory(StoredDirectoryHelper.java:186)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:864)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:353)
	at org.schabi.newpipe.download.DownloadDialog.$r8$lambda$eftfC3lumhpNMhhwp_4dKbyeS0U(DownloadDialog.java:0)
	at org.schabi.newpipe.download.DownloadDialog$$ExternalSyntheticLambda13.onMenuItemClick(R8$$SyntheticClass:0)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

**Comment by fighuass** [comment]
Fixes comments on videos not loading and videos suddenly not working since a short bit ago or so on my end.

**Comment by IMMalebolgia** [comment]
Have tested on a few different FireStick 4k and 4k Max units and have had no issues at all, great work.

**Comment by crapnicki** [comment]
Using RC3, I get this error if I have a video partially played and turn off the phone/background the app. If I go back later to play it again, I get an error until I close out of the video and reopen it.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=si4DTxFUUvM
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux samsung/y2quew/y2q:13/TP1A.220624.014/G986U1UEU6HWHD:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>
 
```
com.google.android.exoplayer2.ExoPlaybackException: Source error
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
 
```
</details>
<hr>

**Comment by crapnicki** [comment]
@opusforlife2 It totally could have, but I was getting so many "Something went wrong" errors, that it's hard to remember.

**Comment by DLL125** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ SE
* __Content Language:__ sv-SE
* __App Language:__ sv_SE
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7790)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8532)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```
</details>
<hr>

**Comment by privacyonly** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux samsung/p3sxxx/p3s:14/UP1A.231005.007/G998BXXU9FWK2:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
	at us.shandian.giga.get.DownloadMission.joinForThreads(DownloadMission.java:814)
	at us.shandian.giga.get.DownloadMission.pauseThreads(DownloadMission.java:518)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:360)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:308)
	at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:145)

```
</details>
<hr>

**Comment by raananelefant** [comment]
Works fine for me on my Fairphone 5 running Android 13
