### ISSUE TITLE
Your own repo is stuck (f-droid) again

### ISSUE THREAD

**Issue by serrq** [TeamNewPipe/NewPipe#11127]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0 your own repo on f-droid

### Steps to reproduce the bug

Pushing "refresh" on Droid-ify. Other repos sync, NewPipe one no.

### Expected behavior

All repo sync properly.

### Actual behavior

Stuck as you can see below.

<img alt="1000113546" src="https://github.com/TeamNewPipe/NewPipe/assets/113377431/42ca39c2-6a1e-484b-8da0-92b87aee55e1" width=468 />

### Affected Android/Custom ROM version

Android 14

### Affected device model

OnePlus CPH2399

### Additional information

I temporarily disabled your repo.
