### ISSUE TITLE
No static method toUnmodifiableList()Ljava/util/stream/Collector; in class Ljava/util/stream/Collectors; or its super classes (declaration of 'java.util.stream.Collectors' appears in /apex/com.android.art/javalib/core-oj.jar)

### ISSUE THREAD

**Issue by PeOS-China** [TeamNewPipe/NewPipe#11292]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.27.1

### Steps to reproduce the bug

**Call the code to parse a YouTube link (https://www.youtube.com/watch?v=aXh4Q8Iw2Zo)** ：

            try {
                Log.d(tag, "flow start ")
                val it = StreamInfo.getInfo(YoutubeService(0), url)
                Log.d(tag, "flow end ")
                val streamItem = when (mode) {
                    IYTDownload.RequestMode.VIDEO -> getBestVideoItem(it.videoStreams)
                    IYTDownload.RequestMode.AUDIO -> it.audioStreams.getOrNull(0)
                }
                Log.d(tag, "onEach 2")
                if (streamItem != null) {
                    pair = Pair(streamItem.content, it.duration)
                } else {
                    val errMsg = "NewPipe error(onEach): can not get stream info at $url"
                    Log.d(tag, errMsg)
                    onError?.invoke(Throwable(errMsg), false)
                }
            } catch (throwable: Throwable) {
                val err = "NewPipe error(throwable): ${throwable.message} at $url"
                Log.d(tag, err)
                val isRemoveErr = postNewPipeError(lessonID, err)
                onError?.invoke(throwable, isRemoveErr)
                Log.d("NewPipe", "requestUrlStreamData catch")
            }

when call  

StreamInfo.getInfo(YoutubeService(0), url) 

 ,**An exception was reported here**:

No static method toUnmodifiableList()Ljava/util/stream/Collector; in class Ljava/util/stream/Collectors; or its super classes (declaration of 'java.util.stream.Collectors' appears in /apex/com.android.art/javalib/core-oj.jar)

### Logs

No static method toUnmodifiableList()Ljava/util/stream/Collector; in class Ljava/util/stream/Collectors; or its super classes (declaration of 'java.util.stream.Collectors' appears in /apex/com.android.art/javalib/core-oj.jar)

### Affected Android/Custom ROM version

Android12

**Comment by Aurangzeb365** [comment]
I'm also facing the same issue.
