### ISSUE TITLE
Background player does not return to Main activity if app was swiped away in Android Task list

### ISSUE THREAD

**Issue by basilgello** [TeamNewPipe/NewPipe#1836]
Steps to reproduce:

1. Open NewPipe, 
2. Select a video to play in background
3. Wait until audio starts playing, then go to Android task bar and swipe the app out
4. Press on navbar notification pane to bring Background player again
5. Press "Back" arrow in top left corner of Background player
6. Get into desktop

Expected behavior:

Step 6 should open Main activity with the video being played.

Attached the screencast of error: https://fex.net/165974815061 (best played with ffmpeg)

- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

**Comment by litetex** [comment]
Closing this issue due to inactivity since nearly 3 years (no upvotes, comments, mentions).

Also the environment has changed:
4. Brings now the playqueue
