### ISSUE TITLE
Voting system for features to be added

### ISSUE THREAD

**Issue by MD77MD** [TeamNewPipe/NewPipe#4418]
### Checklist

- [ ] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

I think there should be a discussion on the best way to implement a voting system.

#### Is your feature request related to a problem? Please describe it

there are a lot of features that are being suggested. however, having a voting system would assist developers in to know on what feature to focas and how much time to spend on it.

#### Additional context

there are many old but more important features that need developers attention but unfortunately they are getting bared by the constant new feature requests..   

#### How will you/everyone benefit from this feature?

the voting system will definitely help current and up coming developers -and whomever wants to get involved- to know exactly what feature is worth there limited time.

P.S: a pined issue explaining how to vote is a good start.

**Comment by Stypox** [comment]
@MD77MD if we were lacking PRs, I would say this is a good idea, but there are already 60+ PRs with new features to review and merge, so I don't think making a list of voted feature requests would count much with actually what features are put into the app

**Comment by opusforlife2** [comment]
Ultimately, what matters is developer interest and time. If no developer is interested in a feature, then it will not be implemented no matter how many more thousands of upvotes it has compared to the item in second place.

I think we won't find such a system useful. Voting is far more useful for choosing between two alternative features a developer wants to test.

Anyway, Github already provides a way to sort issues and PRs by thumbs up and other emojis.

**Comment by wb9688** [comment]
GitHub already has reactions and you could sort by e.g. most :+1:

**Comment by MD77MD** [comment]
even if no system was implemented, i think it sould be discussed at least between developers... perhaps tags can be used to indicate priority (eg: level 1, level 2.) something like that.

>GitHub already has reactions and you could sort by e.g. most 👍

this would be enough if issues/PR could be sorted according to number of reactions, but I doubt it... however, still this is better then nothing. 

i would try to inform visitors some were clear about this, that the newPipe developers consider it as a simple voting system... this would also help to indicate whether a  requested feature is really a nich or not.

**Comment by opusforlife2** [comment]
Hmmm. I wonder if there is a way to have the default issue sorting for visitors to be by the number of thumbs up.
