### ISSUE TITLE
[Meta] Extractor issues in extractor

### ISSUE THREAD

**Issue by kubo6472** [TeamNewPipe/NewPipe#5028]
### Checklist

- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. Technically #3940 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
Adding some clear instructions, that extractor issues should go exclusively to extractor repo and who should be responsible moving them there, etc.

#### Is your feature request related to a problem? Please describe it
I made possibly the greatest "gray-area" example issue for this, as I thought it's an extractor thing, to get newpipe to support "local youtube-dl" like FreeTube, but I formulated the issue like: "switch away from using the extractor" so it was technically a newpipe issue. (Just read it for the context teamnewpipe/newpipeextractor#466)

**Comment by opusforlife2** [comment]
New issue forms solved this.
