### ISSUE TITLE
Bounty Source of Newpipe is not being updated

### ISSUE THREAD

**Issue by tiwarys** [TeamNewPipe/NewPipe#5212]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to [Bounty source of Newpipe](https://www.bountysource.com/teams/newpipe/issues)
2. Click on [YouTube-like UI](https://www.bountysource.com/issues/85796004-youtube-like-ui)
3. It shows Bounty source of [YouTube-like UI](https://www.bountysource.com/issues/85796004-youtube-like-ui) is open but corresponding issue in github is [closed](https://github.com/TeamNewPipe/NewPipe/issues/2882).
4. 
![Newpipe](https://user-images.githubusercontent.com/46630255/102581899-7e188c00-4127-11eb-8fdb-6aa5bff68f23.png)

See the Bounty Source row of [donate](https://github.com/TeamNewPipe/NewPipe#donate), it always shows **bounties|invalid response data**. Try to display bounties data.

### Expected behavior

1. [YouTube-like UI](https://www.bountysource.com/issues/85796004-youtube-like-ui) needs to closed on Bounty Source.
2. Bounties data need to be displayed in [donate](https://github.com/TeamNewPipe/NewPipe#donate)

**Comment by Stypox** [comment]
@TobiGr do you have administrator rights for this?

**Comment by AudricV** [comment]
This issue is not relevant anymore: see https://newpipe.net/blog/pinned/announcement/we-have-lost-access-to-bountysource/ and #10491. Closing as outdated.
