### ISSUE TITLE
Jcenter will shut down soon

### ISSUE THREAD

**Issue by Atemu** [TeamNewPipe/NewPipe#5837]
I wanted to build NewPipe today but there's a jcenter outage and I'm unable to fetch the dependencies.

When googling for potential mirrors, I found this: https://blog.gradle.org/jcenter-shutdown

O_o

I wasn't even able to fetch the kotlin plugin with a clean GRADLE_USER_HOME. It's in mavenCentral too thankfully but even with that I get stuck at trove4j which isn't in mavenCentral nor Google's repo.

Apparently jcenter will go readonly at the end of the month, so this patch will need to be made to work rather soon if we want security patches from that point on:

```diff
diff --git a/build.gradle b/build.gradle
index b2593ab42..4f23e4b5e 100644
--- a/build.gradle
+++ b/build.gradle
@@ -3,7 +3,6 @@
 buildscript {
     ext.kotlin_version = '1.4.10'
     repositories {
-        jcenter()
         google()
     }
     dependencies {
@@ -17,7 +16,6 @@ buildscript {
 
 allprojects {
     repositories {
-        jcenter()
         google()
         maven { url "https://jitpack.io" }
         maven { url "https://clojars.org/repo" }
-- 
```

### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TobiGr** [comment]
Thank you for letting us know!
I have created PR to remove JCenter when possible: #5843
I could not resolve these dependencies:
```
com.google.android.exoplayer:exoplayer:2.11.8
com.google.android.exoplayer:extension-mediasession:2.11.8
com.nononsenseapps:filepicker:4.2.1
com.xwray:groupie:2.8.1
com.xwray:groupie-viewbinding:2.8.1
org.jetbrains.trove4j
```
https://github.com/google/ExoPlayer/issues/5246#issuecomment-797438415
https://github.com/lisawray/groupie/issues/384
https://github.com/spacecowboy/NoNonsense-FilePicker NoNonsesnse FilePicker is working on migrating their dependencies to Maven Central. For this reason, I guess we can expect to see their binaries published there, soon.

@Atemu Were you able to resolve any of those dependencies?

**Comment by Atemu** [comment]
My attempts didn't go much further than trying to get stuff from mavenCentral() instead either.

For some dependencies like trove, jcenter going readonly might not be *that* bad as it hasn't seen an update in years anyways.  
Your approach of explicitly whitelisting these is the best we could do right now I think.

**Comment by OxygenCobalt** [comment]
Looks like [Exoplayer](https://github.com/google/ExoPlayer/releases/tag/r2.13.3) and `trove4j` have both moved to mavenCentral/GMaven. You may want to update #5843 to reflect that?
