### ISSUE TITLE
Release 0.21.0

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#5872]
# Changelogs
### New
- Added new service: [Bandcamp](https://bandcamp.com) #3741  Many thanks to @fynngodau!

### Improved
- Added setting to match device's theme (dark & black) #3632
- Show improved error panel instead of annoying snackbar or crashing #5148 
- More information on why content is unavailable #5385 
- "pause/play" toggle when pressing hardware keyboard space button #5562 
- Added toast to inform the user that download started #5519 
- Updated User-Agent to resist fingerprinting #5649 

### Fixed
- Fixed very small thumbnails in video detail fragment when playing stream in background #5818 
- Fixed empty stream title in minimized player #5820
- Fixed last resize mode not being restored correctly #5792 

### Development
- Updated prettytime #5230
- Updated ExoPlayer to 2.12.3 #5457 
- Sonar workflow #5844
- Disable sonar job #5906

### New
- Added new service: [Bandcamp](https://bandcamp.com) TeamNewPipe/NewPipeExtractor#232, TeamNewPipe/NewPipeExtractor#579 Many thanks to @fynngodau!

### Improved
- Added more Exceptions specifying the `ContentNotAvailableException` TeamNewPipe/NewPipeExtractor#509
  - `AgeRestrictedContentException`, for age-restricted content which has no video or audio streams.
  - `GeographicRestrictionException`, for georestricted content (used for SoundCloud and YouTube georestricted videos, not working on YouTube Music georestricted tracks because YouTube shows "This video is not available")
  - `PaidContentException`, for paid content like YouTube movies or YouTube videos that require a channel subscription
  - `PrivateContentException`, for private YouTube videos (can be used for other services)
  - `SoundCloudGoPlusContentException`, for SoundCloud Go+ tracks
  - `YoutubeMusicPremiumContentException`, for YouTube videos restricted to YouTube Music Premium members
- [SoundCloud] Support HLS-only tracks by using a workaround TeamNewPipe/NewPipeExtractor#526 
- Update User-Agent to resist fingerprinting TeamNewPipe/NewPipeExtractor#551 

### Fixed
-  [YouTube] Fix trending `getName()` TeamNewPipe/NewPipeExtractor#582 
- [YouTube] Mix playlist - Fix `getName()` TeamNewPipe/NewPipeExtractor#583
-  [Peertube] Fix account subscribers extraction TeamNewPipe/NewPipeExtractor#575 
- [PeerTube] Fix playlist extraction TeamNewPipe/NewPipeExtractor#583

### Development
- Unignore more tests TeamNewPipe/NewPipeExtractor#546 
- Add MockOnlyRule to allow skipping specific tests based on downloader TeamNewPipe/NewPipeExtractor#517 
- [media.cc.de] Disable unreliable tests for now TeamNewPipe/NewPipeExtractor#583 

# TODO
- [x] Merge Weblate (@B0pol could you do this?)
- [x] Fix settings switches being white instead of red #5899
- [ ] ~~Timestamps #5523~~
- [x] Peertube account subscribers TeamNewPipe/NewPipeExtractor#575
- [x] Trending fixes TeamNewPipe/NewPipeExtractor#582
- [x] Error panel crash #5896
- [x] Fix French typos #5907

# APK for testing

[NewPipe_0.21.0_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/6203185/NewPipe_0.21.0_RC3.zip)

Corresponding PR: #5871

**Comment by B0pol** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe.debug.release0210/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.error.ErrorPanelHelper.dispose()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4496)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4515)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4799)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4732)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.error.ErrorPanelHelper.dispose()' on a null object reference
	at org.schabi.newpipe.fragments.BaseStateFragment.onDestroy(BaseStateFragment.java:62)
	at org.schabi.newpipe.fragments.list.BaseListFragment.onDestroy(BaseListFragment.java:96)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.onDestroy(BaseListInfoFragment.java:77)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2927)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:492)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1296)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2609)
	at androidx.fragment.app.Fragment.performDestroy(Fragment.java:2922)
	at androidx.fragment.app.FragmentStateManager.destroy(FragmentStateManager.java:492)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1296)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1504)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2609)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:242)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:458)
	at android.app.Activity.performDestroy(Activity.java:7403)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4481)
	... 13 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Same crash as Bopol, but Step 1 and 2 were searching for a video and opening it. So it is probably Step 4 that causes the crash, regardless of how a video is opened.

**Comment by B0pol** [comment]
No because opening from trending doesn't cause a crash

**Comment by opusforlife2** [comment]
Hmm... then opening from a fragment, maybe?

**Comment by iamthesenate1** [comment]
Error parsing trending page:


## Exception
* __User Action:__ requested kiosk
* __Request:__ Start loading: https://www.youtube.com/feed/trending
* __Content Country:__ RO
* __Content Language:__ ro-RO
* __App Language:__ ro_RO
* __Service:__ YouTube
* __Version:__ 0.21.0
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Trending name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getName(YoutubeTrendingExtractor.java:84)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:70)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:183)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$NbG7JFGg0N9HK-3exJNRB9r_hYY.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

```
</details>
<hr>

**Comment by Stypox** [comment]
I ran `git bisect`, the wrong switches color is caused by 731c65cd59e72921389c114f5f5ba4da8374336c

**Comment by Disqu3-mirOir-qt** [comment]
## Exception
* __User Action:__ requested kiosk
* __Request:__ Start loading: https://www.youtube.com/feed/trending
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr
* __Service:__ YouTube
* __Version:__ 0.21.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Trending name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getName(YoutubeTrendingExtractor.java:84)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:70)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:183)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$NbG7JFGg0N9HK-3exJNRB9r_hYY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)

```
</details>
<hr>

**Comment by Stypox** [comment]
@Disqu3-mirOir-qt see the comment above: https://github.com/TeamNewPipe/NewPipe/issues/5872#issuecomment-805357876

**Comment by Stypox** [comment]
Release candidate 2: [NewPipe_0.21.0_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/6202670/NewPipe_0.21.0_RC2.zip)
- Merged weblate #5904
- Fix settings switches being white instead of red #5899
- Trending fixes TeamNewPipe/NewPipeExtractor#582
- Error panel crash #5896

**Comment by Stypox** [comment]
Release candidate 3: [NewPipe_0.21.0_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/6203185/NewPipe_0.21.0_RC3.zip)
- Fix French typos #5907
- Update extractor with trending fixes
