### ISSUE TITLE
[SonarQube] Allow skipping code analysis

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#5890]
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Allow to skip the SonarQube code analysis if the developer thinks, that it is not needed. We have a bunch of PRs which do not alter code, e.g. changes to gradle files, README or translation updates, ...

This can be done by adding a new checkbox to the PR template:
- [ ] Skip SonarQube code analysis.

We should also add a short description when SonarQube can be skipped.

In the workflow, we can check if the checkbox is checked and abort if necessary.

#### Is your feature request related to a problem? Please describe it
Running code analysis on PRs which do not alter code puts load on their servers and thus creates cots (electricity, storage, CPU time, ...) which we do not pay for. So we should only run that stuff when it is necessary.

#### How will you/everyone benefit from this feature?
Shorter workflow times :)

**Comment by XiangRongLin** [comment]
This issue is outdates as the feature is already implemented in the meantime.
