### ISSUE TITLE
Add translations for "No Login Required" in corresponding Readme.md files

### ISSUE THREAD

**Issue by sauravrao637** [TeamNewPipe/NewPipe#6240]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Task
Translations for feature "No Login Required" needs to be added in Readme files of corresponding languages.
Related [PR#5994](https://github.com/TeamNewPipe/NewPipe/pull/5994)
