### ISSUE TITLE
"Debugger" NewPipe for better logs?

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#6267]
Edited Twice: Revision and polishing.

### Checklist
- [x] I checked, but didn't find any direct duplicates (open OR closed) of this issue in the repo. (although I would like to declare I am not very good with computers) 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want implimented
I would like to suggest a "debugger" function or version in/of NewPipe (the RC versions that are provided for testing [in the issues section] before a new version is released notwithstanding) that in tandem with the error reporting functionality already present; would make a detailed log [similar to an adb-logcat] providing more accurate and useful information for the NP-Team here to understand and investigate errors when a "report" option is not shown or an error cannot be reproduced. 

#### Is your feature request related to a problem? Please describe it
The request is related to issues that do not inherently provide a report button, therefore no logs that can be used to help the bug-fixing process. It would be a very useful addition to the application.

#### Additional context
1) I am aware of comments [https://github.com/TeamNewPipe/NewPipe/issues/6207#issuecomment-830696742 - for example] that could be seen as further evidence that my request has merit.
2) I am also aware that there are comments [https://github.com/TeamNewPipe/NewPipe/issues/4201#issuecomment-683668294] suggesting a debug version of newpipe be used in tandem with chrome to get "HAR" with content. Another aspect that I would like to bring forward for consideration as an addition.

The above notwithstanding, I would also like to request (and I apologize if I should make it another issue) a way to directly obtain a means to obtain a [pre-built] version of the currently available debug apk (as mentioned in "4."
of the "Installation and update" section of https://github.com/TeamNewPipe/NewPipe#readme) on the GitHub main page. Because I do not have the technical understanding to build it myself.

#### How will you/everyone benefit from this feature?
Everyone using NewPipe would have the means to not only provide but also help to pinpoint (I assume) the reason(s) for certain bugs and in-turn provide better information for the respectable members that can provide a bug-fix.
Moreover, the pre-built debug APKs would be useful for fellow users (myself included) that are not as technically astute and/or unable to do so. 

Thank you for your time and consideration.
___
### Additional Notes
1) PS. Would someone be willing to teach/explain to me (and anyone reading this) how to do "labels" because I assume that what I additionally requested may merit a 'meta' label, [though I may be wrong] and I would like to be able to add relevant ones in future issues/requests.

2) PPS: I apologize if there is already an existing method of obtaining a pre-built debug apk; I am not aware of it personally and would appreciate it if someone could link me in the right direction. 
I have searched: 
A) The "https://newpipe.net (and the "/FAQ/" section of) site
B) The readme.md [which mentioned a debug apk] document, previously stated above.
C) The Wiki (https://github.com/TeamNewPipe/NewPipe/wiki/Additional-Debugging-Info) [Mentioning not only a debug apk but the HAR+Chrome method also previously stated in "2):" of the 'additional context' of this request.
As well as (but not limited to) the issues, releases and projects sections of the GitHub. but was unable to locate it.

Once again, thank you for your time and consideration.
Stay safe, Be well.

**Comment by TiA4f8R** [comment]
About the labels, only users with triage rights have the permission to add labels, not everyone.

About logs, I may be wrong, but I think that I will be not possible until you grant the permission `android.permission.READ_LOGS` manually with ADB (and on EMUI devices, you need to start the Project Menu by using the stock dialer app to enable log access).
