### ISSUE TITLE
Github artifacts "app.zip" extraction error

### ISSUE THREAD

**Issue by skyGtm** [TeamNewPipe/NewPipe#6286]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Screenshots/Screen recordings

The artifacts downloaded is corrupted.
Errors while extracting app.zip obtained from artifacts tab. I tried WinRAR, 7zip and windows explorer extractor.

![Capture](https://user-images.githubusercontent.com/50160188/118248837-784f8880-b4c4-11eb-9b5d-e1f5c3f81b75.PNG)
![Capture2](https://user-images.githubusercontent.com/50160188/118248841-7980b580-b4c4-11eb-9948-6582576d7f39.PNG)
![Capture3](https://user-images.githubusercontent.com/50160188/118248849-7c7ba600-b4c4-11eb-9288-ba86c35e0269.PNG)

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TiA4f8R** [comment]
That's strange. From what workflow did you get the archive and which browser are you using? Have you tried to copy the ZIP file to your phone then extracting the APK with it using Android's Files app or with another file manager?

**Comment by skyGtm** [comment]
Yes its windows 8.1
I tried extracting zip from Android file manager too.

Turns out its the browser  the `Edge browser` which corrupted the file.
I used another browser and now it is extractable, without any errors.
Sorry for this issue.
