### ISSUE TITLE
[meta] Wikipedia article

### ISSUE THREAD

**Issue by TheAssassin** [TeamNewPipe/NewPipe#666]
I'd love to see a Wikipedia article (or even localized ones) for NewPipe. I assume the app is mature enough by now, and there's enough references one could use in my opinion.

I'd love to see our contributors compose an article about this really awesome piece of software.

@theScrabi and I put a list of references together you might use (a few are in German, and it would be awesome to see those magazine articles as references):

  - https://newpipe.schabi.org
  - https://www.xda-developers.com/latest-newpipe-update-lets-you-control-the-playback-speed-of-youtube-videos/
  - https://f-droid.org/packages/org.schabi.newpipe/
  - https://fossdroid.com/a/newpipe.html
  - https://www.maketecheasier.com/open-source-youtube-app-android/
  - https://androidcommunity.com/updated-newpipe-adds-option-to-change-speed-of-playback-20170720/
  - https://hosted.weblate.org/projects/newpipe/
  - https://events.ccc.de/congress/2016/wiki/Session:NewPipe
  - https://www.slashgear.com/newpipe-youtube-android-app-with-more-controls-and-no-google-20492117/
  - http://stadt-bremerhaven.de/newpipe-erlaubt-das-abspielen-von-youtube-videos-wenn-der-bildschirm-aus-ist/
  - http://stadt-bremerhaven.de/youtube-audio-im-hintergrund-ohne-zusatz-apps/
  - https://ausdroid.net/2016/02/17/newpipe-a-youtube-downloading-app/
  - https://www.android-arsenal.com/details/3/2949
  - http://phandroid.com/2017/08/30/youtube-picture-in-picture-without-youtube-red/
  - https://android.gadgethacks.com/news/10-awesome-android-apps-you-wont-find-google-play-0168598/
  - https://www.heise.de/ct/ausgabe/2016-2-Android-ohne-Google-und-Hersteller-Apps-nutzen-3057405.html (a German magazine, you should refer to the printed version when using this)
  - https://www.heise.de/ct/ausgabe/2017-4-Quellen-fuer-Apps-abseits-vom-Play-Store-3610718.html
  - https://www.youtube.com/watch?v=Wj8kLUoUZ6A
  - https://www.gtricks.com/youtube/floating-window-background-audio-android/
  - https://droid-break.info/
  - https://www.quora.com/Which-is-the-best-You-Tube-video-download-app-for-Android?share=1
  - https://www.linkedin.com/pulse/newpipe-lightweight-youtube-frontend-android-saifuddin-slatewala
  - http://techwiser.com/play-youtube-videos-in-background-android/
  - http://thetechnews.org/newpipe-youtube-android-app-with-more-controls-and-no-google/
  - https://www.nextgeekers.com/2017/08/30/how-to-free-download-complete-youtube-playlist-on-android/

**Comment by comradekingu** [comment]
https://en.wikipedia.org/wiki/NewPipe

- [ ] Add images
- [ ]  Find Google Play terms where it says YouTube frontends, or whatever may be the issue, are not allowed.
- [ ] Populate with links
- [ ] Include more info about format support etc.

**Comment by TheAssassin** [comment]
Thanks @comradekingu! Awesome to see someone's picked up my idea!

As images, you can use the screenshots published in this repository. They're under the GPL v3 license, and can thus be used on Wikipedia.

The apps are not allowed due to their Terms of Service if I remember correctly. @theScrabi please elaborate.

Please post the links you want to have, and we'll send you some.

Something I noticed is that the authors list contains "TeamNewPipe". Please use "Team NewPipe" instead, the former is just the short name for the GitHub URL.

**Comment by comradekingu** [comment]
https://commons.wikimedia.org/wiki/File:NewPipelogo.svg
Needs a screenshot

**Comment by theScrabi** [comment]
No thats just right that way :)

**Comment by comradekingu** [comment]
The file says it will be deleted if correct licensing information isn't added.
Doing it through the editor only dropped "GPLv3" outside of the field, and none of the other cryptic information seems to help.

**Comment by TheAssassin** [comment]
@comradekingu I have to note that now, it's "Team New Pipe", but since the app itself is called "NewPipe" (no space), it's "Team NewPipe". I hope you don't mind me being a little pedantic about this, but it should be correct.

**Comment by coffeemakr** [comment]
NewPipe could also be added to the article ["Comparison of YouTube downloaders"](https://en.wikipedia.org/wiki/Comparison_of_YouTube_downloaders)

Maybe this link could be used for Google Play terms violation: https://play.google.com/about/ip-deception-spam/impersonation-ip/encouraging-infringement/

**Comment by comradekingu** [comment]
@coffeemakr I had a go, still got the functionality section to do.

The format support looks to me like NewPipe doesn't do any lossy transcoding, whereas 3GP is mentioned as one of the converted formats. Is that upstream?

**Comment by theScrabi** [comment]
Yes, NewPipe is not capable of converting anything.

**Comment by TobiGr** [comment]
NewPipe is No. 14 trending project today 🎉 
I tried to find the reasons for that. I guess one big reason is the release of 0.10.0. I also saw [this](https://www.reddit.com/r/Android/comments/711pki/newpipe_the_opensource_youtube_client_with/) Reddit post wich was opend only one day ago and has more than 800 comments and 6500 views now. I think we can use it also for TeamNewPipe/website#33. Maybe we should do some more blogging on platforms like medium, reddit etc.
I'd like to add these links to the list above:
http://techpp.com/2017/09/19/play-youtube-videos-background-android-newspipe/
https://android.com.pl/aplikacje/98040-newpipe-alternatywna-aplikacja-youtube/ (Polish and quite long)

**Comment by theScrabi** [comment]
Yösss :)

**Comment by TobiGr** [comment]
I found this detailed and long article about NewPipe. It's really good: https://www.androidsage.com/2017/09/23/download-newpipe-advanced-youtube-experience-apk/

**Comment by TheAssassin** [comment]
@TobiGr the problem is that the article is marked for deletion:

>  | This article is being considered for deletion in accordance with Wikipedia's deletion policy.Please share your thoughts on the matter at this article's entry on the Articles for deletion page.Feel free to edit the article, but the article must not be blanked, and this notice must not be removed, until the discussion is closed. For more information, particularly on merging or moving the article during the discussion, read the guide to deletion.
-- | --

We need to do something about it, I guess.

**Comment by theScrabi** [comment]
Yep our wikipedia artikle got removed.

But we are now listed here:
https://de.wikipedia.org/wiki/Liste_von_freien_und_Open-Source-Android-Applikationen

**Comment by kristbaum** [comment]
You now have a english: https://en.wikipedia.org/wiki/NewPipe and a german one https://de.wikipedia.org/wiki/NewPipe . Also somebody has already translated it to spanish: https://es.wikipedia.org/wiki/NewPipe

**Comment by kristbaum** [comment]
Aside from expanding them, I guess this can now be closed :+1:

**Comment by kristbaum** [comment]
@TheAssassin yeah, had to discuss the importance of NewPipe a few times, but by now there is enough media coverage to warrant the article. In the german wiki there was an even longer discussion, but it should be all resolved by now :smiley:

**Comment by TheAssassin** [comment]
Thanks. It's great to see users contribute in so manifold ways!

**Comment by B0pol** [comment]
We do not respect the spirit of Wikipedia IMO, which should be neutral.

Therefore, add this in controversy section (if it doesn't exist, create it):
- missing functionalities. However we can say each update reduce the amount of missing functionalities, maybe?
- Not able to login to Google (+ explain why, and source with [FAQ](https://newpipe.schabi.org/FAQ/bugs/)).

Also, [German page](https://de.wikipedia.org/wiki/NewPipe) is really outdated (not updated since 0.13) and same thing for the [Ukranian page](https://uk.wikipedia.org/wiki/NewPipe).

**Comment by nschulzke** [comment]
I know this hasn't been touched in a while, but I'd suggest re-closing this issue. I don't think this is the place to discuss improvements to an existing Wikipedia article, *especially* if we want the article to end up with a neutral POV. That discussion should happen on Wikipedia itself, in the Talk page: https://en.wikipedia.org/wiki/Talk:NewPipe.

**Comment by Julmik647** [comment]
The English article doesn't exist anymore, but there articles in other languages are still avaiable.
