### ISSUE TITLE
Release 0.21.9

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#6841]
# APK for testing
From GitHub Actions: [NewPipe_v0.21.9_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/6961141/NewPipe_v0.21.9_RC2.zip)

Corresponding pull request: #6840

# TODO

- [x] Push changelog to Weblate (@B0pol could you do this?)
- [x] Merge #6814
- [x] Merge #6847
- [ ] Pull from Weblate just before merging
- [ ] Update extractor version

# App changelog 

### New
- Added comments disabled functionallity #6483 
- Player seekbar thumbnail preview #6434 
- Add ability to mark a feed item as watched #6773 
- Show hearts in comments #6741 

### Improved
- Improved metadata layout, better tags accessibility #6463 
- Various improvements to the player (e.g. faster closing) #6566
- Apply service theme to UI components #6456 #6771 #6847

### Fixed
- Made the thumbnail in the minimized player visible again #6616 
- Fixed 'Unrecoverable player error occurred' when rotating device while playing a video #6503
- Fix duplicate items in queue causing endless buffering #6712 
- Delete pending missions with invalid storage fixing a crash when starting a download #6721 #6778 
- Prevent ReCAPTCHA webview from keeping YouTube loaded in background #6733 
- Disable feed click events while refresh overlay is shown #6550 
- Fix channel item span count for SubscriptionFragment #6814 

### Development
- Upgraded Gradle #6538 
- Updated some libraries #6540, #6702
- Specify emulator-build version in CI job fixing emulator build #6560 
- Do not immediately commit preference changes on import #6531 
- Fix API level 29 from android ci tests #6678, #6715  
- Use GestureDetectorCompat #6637 
- Add instrumented tests for LocalPlaylistManager.createPlaylist #5531 #6706 
- Bump compileSdkVersion to 30 #6654
- Fix some build warnings #6688 
- Added a Kotlin section in CONTRIBUTING.md #6659 
- Use Kotlin methods in LicenseFragment #6675
- Use WindowInsetsCompat's getInsets() method #6689
- Consolidate edittext alert dialogs into one common layout #6720 
- Fix deprecated fill_parent attributes #6782
- Check formatting of kotlin files in CI #6808 
- Update some AndroidX libraries #6719
- Use NotificationChannelCompat #6633

**Comment by SameenAhnaf** [comment]
Is this intended? The seek bar and buffering icon are red for every single service.
![IMG_20210804_163144](https://user-images.githubusercontent.com/79245641/128166790-3cd93303-b61b-4973-88f9-4bb51c1090c8.jpg)

**Comment by Movisivi** [comment]
If I download this will it auto update or will I have to download another APK to get back on schedule?

**Comment by SameenAhnaf** [comment]
@Movisivi No, this is a test apk. It's not a mainstream release. It will NOT install over your main app rather as a separate app.

It's released to make sure that users don't encounter bugs. A stable apk will be released later once the bugs (if bugs do exist) are fixed.

**Comment by Stypox** [comment]
> The seek bar and buffering icon are red for every single service. 

The color depends on the currently chosen service, not on the video currently being played. Then again, maybe you actually had SoundCloud selected.

Btw, when you send screenshots, could you please make them properly sized? Use `<img src="INSERT_LINK_HERE" height="300px"/>`. Hint: you cann add this as a saved github reply so that you don't have to learn it by heart. I've edited your comment

**Comment by Stypox** [comment]
@SameenAhnaf does #6847 solve it?

**Comment by flopezre** [comment]
Error to download video:
```
## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=V25KzeuREj4 [ {type=video format=MPEG-4 quality=1080p60 videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Country:__ US
* __Content Language:__ es-US
* __App Language:__ es_US
* __Service:__ YouTube
* __Version:__ 0.21.8
* __OS:__ Linux samsung/a70qxtc/a70q:11/RP1A.200720.012/A705MNXXU5DUC6:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.io.EOFException: parser go beyond limits of the box. type= offset=26990656 size=0 position=26990664
	at org.schabi.newpipe.streams.Mp4DashReader.ensure(Mp4DashReader.java:311)
	at org.schabi.newpipe.streams.Mp4DashReader.getNextChunk(Mp4DashReader.java:182)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.getNextSample(Mp4FromDashWriter.java:407)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.getNextSample(Mp4FromDashWriter.java:416)
	at org.schabi.newpipe.streams.Mp4FromDashWriter.build(Mp4FromDashWriter.java:333)
	at us.shandian.giga.postprocessing.Mp4FromDashMuxer.process(Mp4FromDashMuxer.java:22)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:174)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:703)
	at us.shandian.giga.get.DownloadMission.lambda$J0GR1urTFneOp2O30GpOM3TNG0I(Unknown Source:0)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$J0GR1urTFneOp2O30GpOM3TNG0I.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

```

**Comment by skyGtm** [comment]
The colors are not changed according to selected service for these sections :
1. Downloads
2. Settings
3. About

Is this intended behaviour?

**Comment by SameenAhnaf** [comment]
@skyGtm Technically, these three sections behave the same for all services at least for now. So, I guess, changing these sections' colours might be unnecessary or even misleading as the differenciation is of no use.

**Comment by Stypox** [comment]
@flopezre could you provide more info? Android version, the video you were downloading, resolution, audio/video, SAF or non-SAF, ...

**Comment by enessgokalp** [comment]
![Screenshot_20210805-163811](https://user-images.githubusercontent.com/57983747/128359482-eba9f86a-2c0d-4538-8c8b-340a72973ff7.jpg)
Thumbnail is blurry, but when you enter the video, it is of good quality

**Comment by Stypox** [comment]
> Thumbnail is blurry, but when you enter the video, it is of good quality

Has that something to do with youtubei @TiA4f8R

**Comment by flopezre** [comment]
> @flopezre could you provide more info? Android version, the video you were downloading, resolution, audio/video, SAF or non-SAF, ...

Android version: 11
Video: https://www.youtube.com/watch?v=V25KzeuREj4 (Russian ASMR)
Resolution: 1080p
Audio/Video: Yes (?)
SAF: Yes (?)

**Comment by Stypox** [comment]
@flopezre I could download it just fine. But it's 2.19GB, so I guess that's causing the issue. Are you sure you have enough free space on disk? And are you sure your filesystem supports files that big? Anyway, I don't think that crash is related to the new release, as we didn't change anything regarding the downloader. @kapodamy could you check that stacktrace?

**Comment by SameenAhnaf** [comment]
[0](9) is ⁹9

**Comment by flopezre** [comment]
@Stypox ok, i try to reinstall.

**Comment by bookkojot** [comment]
Age-restricted videos fixed?

**Comment by TiA4f8R** [comment]
> > Thumbnail is blurry, but when you enter the video, it is of good quality
> 
> Has that something to do with youtubei @TiA4f8R

@Stypox The issue is present since a while ago, (I can reproduce it on the current version) and is an extractor issue: see https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeStreamInfoItemExtractor.java#L238-L240

Here is the commit which added this code: https://github.com/TeamNewPipe/NewPipeExtractor/commit/b88188d4198ec81d0d4d78c2b55a07a53a073769#diff-2d29793b2428b5ed716b13435abfad6b7af77d412b65dfcb513998610f69e444

This commit may be however not responsible of the current issue, lower thumbnails may have been added by YouTube after the code was implemented in the extractor.

**Comment by opusforlife2** [comment]
> Age-restricted videos fixed?

@bookkojot Some, not all.

**Comment by Frouk3** [comment]
Add this thing? #6828

**Comment by bew** [comment]
I'm using the pre-release app for 0.21.9 (with SAF enabled) and I experience #6667, which was supposedly fixed and released in 0.21.7...
(was about to open a new issue for this)

**Comment by Stypox** [comment]
Mmmh no, #6667 is unrelated. At least your app doesn't crash. I don't know if that happened in previous versions, too, or if this is a regression. Anyway, I took a look at the code and found two things that could queue the download without starting it:
- you have the "Limit download queue" setting activated and you have already one download running, but that doesn't seem the case by looking at your video
- the network might be unavailable. By looking at the video, you seem not to have a stable connection, so maybe this could be the case.

Anyway, could you send a screenshot of your download settings screen? thank you ;-)

**Comment by bew** [comment]
> Anyway, could you send a screenshot of your download settings screen? thank you ;-)

Sure! 

![Screenshot_20210809-235332](https://user-images.githubusercontent.com/9730330/128779426-1f5ae571-349f-4c4a-8597-23d4ac2f9f91.jpg)

**Comment by opusforlife2** [comment]
> The colors are not changed according to selected service for these sections :

Maybe we should have a neutral colour for non-service-related sections?

**Comment by SameenAhnaf** [comment]
@opusforlife2 Shouldn't Newpipe app icon itself should be other than red? After all, app icon is one of the core neutral parts.

**Comment by opusforlife2** [comment]
@SameenAhnaf That then affects the familiarity/discoverability factor, which needs a far more detailed discussion as it may hurt the app instead of helping.

**Comment by SameenAhnaf** [comment]
@opusforlife2 Personally, I think that finding a neutral color is too general at this moment. The related PRs #6771 and #6456 actually were supposed to apply theme to each service.

Even if we don't apply neutral color on app icon right now, surely a new issue will be generated. So, it's best to have a discussion on this later.

**Comment by TobiGr** [comment]
[NewPipe_v0.21.9_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/6961141/NewPipe_v0.21.9_RC2.zip)
Changes since RC1:
- Fixed PlayQueue theme
- Fixed grid of channel items
- Updated translations
- [YouTube] Updated supported country list
- [YouTube] Faster iframe-API based player extraction
- Updated the extractor's Gradle version to 7.1.1

**Comment by TheWarnerWife38** [comment]
-------------------------------------
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
-------------------------------------

Help please

**Comment by frans4080** [comment]
and it's still dosen't have support for a .csv file.

**Comment by Disqu3-mirOir-qt** [comment]
impossible import database get error

**Comment by Disqu3-mirOir-qt** [comment]
{
   "user_action":"ui error",
   "request":"ACRA report",
   "content_language":"en-GB",
   "content_country":"GB",
   "app_language":"en_GB",
   "service":"none",
   "package":"org.schabi.newpipe.debug.release0219",
   "version":"0.21.9",
   "os":"Linux Android 8.0.0 - 26",
   "time":"2021-08-11 17:22",
   "exceptions":[
      "android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x43 (has extras) }\n\tat android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1981)\n\tat android.app.Instrumentation.execStartActivity(Instrumentation.java:1636)\n\tat android.app.Activity.startActivityForResult(Activity.java:4762)\n\tat androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)\n\tat androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)\n\tat androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)\n\tat androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)\n\tat androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)\n\tat androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)\n\tat org.schabi.newpipe.settings.ContentSettingsFragment.lambda$onCreatePreferences$0$ContentSettingsFragment(ContentSettingsFragment.java:79)\n\tat org.schabi.newpipe.settings.-$$Lambda$ContentSettingsFragment$IJ0-sY_2nFZ8j0D13C6AQ28cAn0.onPreferenceClick(Unknown Source:2)\n\tat androidx.preference.Preference.performClick(Preference.java:1184)\n\tat androidx.preference.Preference.performClick(Preference.java:1166)\n\tat androidx.preference.Preference$1.onClick(Preference.java:181)\n\tat android.view.View.performClick(View.java:6291)\n\tat android.view.View$PerformClick.run(View.java:24931)\n\tat android.os.Handler.handleCallback(Handler.java:808)\n\tat android.os.Handler.dispatchMessage(Handler.java:101)\n\tat android.os.Looper.loop(Looper.java:166)\n\tat android.app.ActivityThread.main(ActivityThread.java:7529)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)\n"
   ],
   "user_comment":""
}

**Comment by nadiration** [comment]
@Stypox Add #6848??

**Comment by nadiration** [comment]
@Stypox Add #6848?

**Comment by Stypox** [comment]
> get error when try , import database

Your OS does not seem to support SAF, even though it should since it's Android 8. Just disable it in "Settings -> Download -> Use Storage Access Framework". This issue is anyway unrelated to this release.

> @Stypox Add #6848?

@nadiration next release, this release is already made this way.

**Comment by Thewisem** [comment]
This is a problem that I found in this update. 
Steps:
1. Open Newpipe
2. Watch a video for some time
3. Open in popup mode in middle of video
4. Watch for some more time
5. Then go back to original mode
6. See player change
The video goes to the timestamp before the popup mode instead of continuing

**Comment by SameenAhnaf** [comment]
@Thewisem This is an old issue and not exclusive to this release. See: #6472.

**Comment by Thewisem** [comment]
Oops Sorry then

**Comment by SameenAhnaf** [comment]
I found a new bug.

1. Turn system rotation off.
2. Open any landscape video on full screen and swipe down to mini player. The app is set to landscape as expected
3. Open another video.
4. Swipe down before the buffering ends.
5. Notification player stays stuck and needs to be swiped away.

![IMG_20210816_012045](https://user-images.githubusercontent.com/79245641/129490043-d41a9c21-9471-49ce-80d6-b97a87de7f93.jpg)

**Comment by Stypox** [comment]
> I found a new bug.

I can't reproduce

**Comment by SameenAhnaf** [comment]
@Stypox The bug seems to persist for other media player apps on my device. So, pardon me if I did something wrong.

However, 'Mark as Watched' does nothing if watch history is disabled. Shouldn't it be hidden if history is disabled? Or, maybe, support for temporary watch history (until closing the app) could be added.

**Comment by TobiGr** [comment]
> However, 'Mark as Watched' does nothing if watch history is disabled

Will be fixed by #6956

**Comment by kkhwg** [comment]
![Uploading Screenshot_20210824_145335_org.schabi.newpipe.jpg…]()

**Comment by yashpalgoyal1304** [comment]
> Btw, when you send screenshots, could you please make them properly sized? Use `<img src="INSERT_LINK_HERE" height="300px"/>`
https://github.com/TeamNewPipe/NewPipe/issues/6841#issuecomment-892756057 by @Stypox 

hiii, i know this is a bit OT, but thanks a lottttt for sharing this. Up untill now, i painstakingly scaled images down in image editing/manipulating softwares - and that used to take so much time and frustrate me so much. But not any more 😃. This works on gitlab too nice :)

> Hint: you can add this as a saved github reply

how?? 🤔 it showed no such options in that comments 3-dot menu.
![image](https://user-images.githubusercontent.com/19423063/137668994-477766bd-6462-4152-83be-6cffa7baf55d.png)


------
had lost this comment, refound by: [repo:teamnewpipe/newpipe in:comments img src](https://github.com/issues?q=repo:teamnewpipe/newpipe+in:comments+img+src)
