### ISSUE TITLE
Release 0.21.10

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#7066]
# APK for testing
From GitHub Actions: [NewPipe_v0.21.10_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/7154709/NewPipe_v0.21.10_RC3.zip)
**Corresponding pull request** #7063  

# ToDo
- [x] #7056 
- [x] Fix failing database migration #7068 
- [x] #7071
- [x] #7085 
- [x] Update translations
- [x] Fix empty plurals in some translations (yes, again - as always)
- [ ] regression https://github.com/TeamNewPipe/NewPipe/issues/7066#issuecomment-913797859

# App changelog 

### New
7- Added Show Channel Details where it's missing #6919 
8- Allow choosing which types of search suggestions to show #3546 
22- Added support for CSV+ZIP subscriptions (Google Takeout) #6882 
24- Show popup menu when long pressing items in the video player's play queue #6955 
27- Added option to directly open fullscreen when the main player starts #5459 
28- Added darker splash screen for OS dark theme #7055

### Improved
4- Changed dark theme colors to darker variant #6244
6- Replace UniversalImageLoader with Picasso #5928 
9- Change "not available" image from PNG to vector format #6917 
10- Provide mime type to file picker to gray out unselectable files #6820 
23- Explain how to remove tab from main page #6965 

### Fixed
2- Catch errors while processing timestamp-links #6851
3- Added wrapping settings titles to the next line #6952 
12- Re-add sharing of the content name with the "Share" command #6957 
15- Fixed double tapping the replay button #7014 
19- [Android TV] Fix long seekbar jumps when using a DPad #6985
25- Close audio effect control session properly #6993 
26- Fixed some inconsistencies in the error panel #7004 

### Development
1- Added gradle parameter to skip formatKtLint and use in CI #6858
11-  Using Eclipse temurin in GH actions #6995 
14-  Use ExoPlayer default values for buffers #6515 
16-  Use PackageInfoCompat.getSignatures(). #6634 
18- Fixed build problems and updated kotlin #6986 
21- Using integrated cache in actions/setup-java #7002 

### Translation
5- Use custom cancel string everywhere #6848 
13- Added plural forms for download related strings #6930 
17- Reword part of the bug report template #6990 
20- Never use `android.R.string`s and remove unused `add` string #7024 

# Extractor changelog

### New
3-  Add invidious instance EduVid Tubus TeamNewPipe/NewPipeExtractor#712
5- Extract Uploader's Avatar in `StreamInfoItem`s (YouTube and PeerTube) TeamNewPipe/NewPipeExtractor#723, TeamNewPipe/NewPipeExtractor#725 
6-  Make `uploaderVerified` available in StreamInfo TeamNewPipe/NewPipeExtractor#724 

### Fixed 
2- [YouTube] Support `csv` and `zip` subscription import (Google Takeout) TeamNewPipe/NewPipeExtractor#709 TeamNewPipe/NewPipeExtractor#721
4- [SoundCloud] Update client id TeamNewPipe/NewPipeExtractor#722 

### Development
1- Bump `gson` from 2.8.7 to 2.8.8 TeamNewPipe/NewPipeExtractor#718

**Comment by SameenAhnaf** [comment]
Not sure how to reproduce it. But app is crashing every now and then.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.10
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.util.Set
	at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:312)
	at androidx.preference.Preference.getPersistedStringSet(Preference.java:1739)
	at androidx.preference.MultiSelectListPreference.onSetInitialValue(MultiSelectListPreference.java:205)
	at androidx.preference.Preference.onSetInitialValue(Preference.java:1614)
	at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1587)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1311)
	at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1326)
	at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:249)
	at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:170)
	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:345)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
	at androidx.preference.PreferenceFragmentCompat.addPreferencesFromResource(PreferenceFragmentCompat.java:361)
	at org.schabi.newpipe.settings.ContentSettingsFragment.onCreatePreferences(ContentSettingsFragment.java:72)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipe.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:28)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8043)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Bug: With device locked to portrait, the app isn't rotating back to portrait upon tapping Back after the video is finished (and the Replay button is shown). Auto-fullscreen can be on or off.

I just reinstalled the auto-fullscreen APK and this bug exists there as well, which means it just slipped through testing.

If it's possible, this could be an opportunity to change current behaviour so that the app automatically goes back into portrait mode after a video is finished when the device is locked to portrait.

**Comment by litetex** [comment]
I also suffer from this bug when e.g. using the emulator and importing the (not migrated version of the) database over and over again.
I think that might be related to #3546...

Update: I did a bit of digging and it seems like when importing the settings the migration method is never called :/
Looks like https://github.com/TeamNewPipe/NewPipe/pull/6495 doesn't do it's job...

**Comment by SameenAhnaf** [comment]
@opusforlife2 Shouldn't #5967 also be solved then?

**Comment by opusforlife2** [comment]
> You have to enable autorotate to fix it.

That's not the case. As I said above, you can simply tap Back to rotate back to portrait.

But also as I've said above, I agree that this bug should be fixed properly if possible. Automatic return to portrait after the video is finished. OR, just stay in landscape fullscreen and exit directly to portrait upon tapping Back (instead of automatically going into a weird non-fullscreen but landscape hybrid.)

**Comment by litetex** [comment]
Created a fix for the failed migrations here: https://github.com/TeamNewPipe/NewPipe/pull/7068

**Comment by TiA4f8R** [comment]
The color of the action bar (back, home, recent apps) is not using the darker red when the system is in dark mode:

https://user-images.githubusercontent.com/74829229/132558145-f5c930b8-ebdc-433e-af65-1b37fcd9c59e.mp4

Is there any way to change this?

**Comment by litetex** [comment]
@TiA4f8R 
Checkout #7085 😄

**Comment by TobiGr** [comment]
Changes in RC2: [NewPipe_v0.21.10_RC2.zip](https://github.com/TeamNewPipe/NewPipe/files/7145294/NewPipe_v0.21.10_RC2.zip)
- Fixed navbar color in darkmode #7085 
- Fixed toggeling description visibility while a video detail is shown #7056 
- Fixed OnErrorNotImplemeneted crashes when trying to play in popup or getting search suggestions #7056
- Reduce battery consumption by changing player progress bar update interval from 0.5s to 1s #7071

**Comment by SameenAhnaf** [comment]
Player progress doesn't update properly when the speed is above 2x.


https://user-images.githubusercontent.com/79245641/132966241-8a2d48c6-971e-4e7a-91f2-2365851f7119.mp4

**Comment by litetex** [comment]
@SameenAhnaf 
This also happens currently (0.21.9) if you e.g. set the speed to 3x.
I think this is fine as more updates would cause more battery usage as described in #7071

**Comment by TobiGr** [comment]
Changes in RC3, which is likely the last RC [NewPipe_v0.21.10_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/7154709/NewPipe_v0.21.10_RC3.zip)
- Updated translations
- Fixed restarting app correctly after importing an old app database

**Comment by XiangRongLin** [comment]
Note that the JitPack release for the extractor failed. https://github.com/TeamNewPipe/NewPipeExtractor/issues/728

If it can't be resolved until this releases the commit hash has to be used instead of the version tag

**Comment by opusforlife2** [comment]
@TobiGr This regression is still unfixed: https://github.com/TeamNewPipe/NewPipe/issues/7066#issuecomment-913797859

**Comment by Pentaphon** [comment]
> This regression is still unfixed:

I can't wait for that to be fixed. As somebody who is always using portrait mode, it is currently the most annoying part of using Newpipe. It keeps getting stuck until I back out of it.

**Comment by Stypox** [comment]
cf9b482be25b412f183635cb0fc4bfc877c7d035 is the first bad commit causing https://github.com/TeamNewPipe/NewPipe/issues/7066#issuecomment-913797859
...do I hate the player code, those changes have **nothing** to do with rotating the device when pressing back...
I will try to fix this later today

**Comment by opusforlife2** [comment]
@Stypox Maybe in the occasionally pinned features/bugs issue for devs, we could add an item: "Refactor the massive Player code into smaller, more manageable components".

**Comment by Stypox** [comment]
@opusforlife2 regression fixed in 7667b2ce59ce76be93830d390284be624bce3ba5 (please confirm)
Btw, the cause of the problem was an `if` checking if the player is open before restoring the orientation, so it used to work because the player was not closed correctly. So this confirms that #5459 indeed correctly closes it ;-)
RC4: [NewPipe_v0.21.10_RC4.zip](https://github.com/TeamNewPipe/NewPipe/files/7192559/NewPipe_v0.21.10_RC4.zip)

**Comment by mhmdanas** [comment]
Is anything blocking this issue getting closed? The corresponding PR has already been merged.

**Comment by Pentaphon** [comment]
> Is anything blocking this issue getting closed? The corresponding PR has already been merged.

I guess the last commit has to be confirmed and it's ready to ship.

**Comment by opusforlife2** [comment]
Wow that was fast. Yes indeedy! The regression has been fixed. Release the ostriches!
