### ISSUE TITLE
Release v0.24.0 (please TEST!)

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#8890]
## Testing for regressions
Debug APK (built by our CI in #8889): [NewPipe_v0.24.0_RC3_debug.zip](https://github.com/TeamNewPipe/NewPipe/files/9597719/NewPipe_v0.24.0_RC3_debug.zip)
Release APK (built and signed by @Stypox): [NewPipe_v0.24.0_RC3_release.zip](https://github.com/TeamNewPipe/NewPipe/files/9597686/NewPipe_v0.24.0_RC3_release.zip)
Please report **only regressions** (i.e. new issues) here, not issues that were already present in previous releases!

## TODO

- [x] Merge weblate
- [x] #8899
- [x] TeamNewPipe/NewPipeExtractor#920
- [x] TeamNewPipe/NewPipeExtractor#925
- [x] TeamNewPipe/NewPipeExtractor#926
- [x] Thumbnails in the feed tab are incorrectly resized https://github.com/TeamNewPipe/NewPipe/issues/8890#issuecomment-1236708859 https://github.com/TeamNewPipe/NewPipeExtractor/pull/927
- [x] Strange `Show future videos` icon behavior https://github.com/TeamNewPipe/NewPipe/issues/8890#issuecomment-1230466338 #8966
- [ ] Crash when closing mini player before it loads https://github.com/TeamNewPipe/NewPipe/issues/8890#issuecomment-1242885157 https://github.com/TeamNewPipe/NewPipe/issues/8646#issuecomment-1236162209
- [x] Search suggestions ListAdapter issues #8972

## NewPipeExtractor version

This version of NewPipe will ship with NewPipe Extractor commit https://github.com/TeamNewPipe/NewPipeExtractor/commit/5c710da160f488bb40ab2cf4469bec9bd4cefd38.
-> we are going to change the exposed extractor API again soon, so no official release will be done until then ;-)

<details><summary><h2>App changelog </h2></summary><p>

### New
- :warning: Bump `minSdk` to 21 (Android 5 Lollipop) and **drop support for Android 4.4 KitKat** #7613
- Add Download entry to long-press menu #8397 
- Add option to hide future videos in feed #8545
- Add Share menu item to local playlists #8542

### Improved
- Crop the notification thumbnail in 1:1 mode instead of stretching it #8533
- Make thumbnails' `scaleType` `fitCenter` #8573 
- Improve image placeholders #8530
- Removed the "(beta)"-tag from services #8637 
- Refactor player and extract UI components #8170 #8661 #8678 #8731
- Sort tags case-insensitively #8709
- Use ListAdapter for search predictions #8719

### Fixed
- Fix wrong image used as a placeholder for channels avatars #8676 
- Fix various issues with player notification #8678

### Localization
- Make some much needed changes to the README #8372
- Fix lang code for Chinese Simplified #8549

### Development
- Run CI on all release branches #8565
- Clean up proguard file #8468
- Update ExoPlayer to 2.18.1 #8536 #8687
- Specify used ExoPlayer libraries #8469
- Use minimum required permissions for GitHub workflows #8569
- Checkstyle assign on same line #8601
- Use `ViewCompat.setBackgroundTintList()` #8633 
- Update some misc libraries #8475
- Use stream sorting #8635 
- Use Java 9 collection factories: `List.of()`, `Set.of()`, `Map.of()` #8631 #8679
- Use range-limiting method `MathUtils.clamp()` #8651 #8737
- Use Kotlin IO extensions #8648 
- Remove some unnecessary methods #8663 #8740 
- Remove deprecated method calls in `FocusAwareCoordinator` #8670 
- Deduplicate SQL queries to get feed streams #8621
- Update OkHttp to 4.10.0 #8624 
- Update Lifecycle to 2.5.1 #8683
- Update AndroidX Fragment to 1.4.1 #8691
- Update Google Material to 1.6.1 #8692 
- Use `Throwable.stackTraceToString()` #8701 
- Update AppCompat to 1.4.2 #8667 
- Use WindowMetrics API #8656
- Update AndroidX Room to 2.4.3 #8716 
- Remove uses of `setBottomSheetCallback()` #8669 
- Refactor `LicenseFragmentHelper` #8682
- Make `OnClickGesture` an interface #8721 
- Reduce `View.kt` size #8708 
- Use `toArray()` with zero-length arrays #8724 
- Use `Comparator` factory methods #8728 
- Use `Collectors.joining()` #8738 
- Update FilePicker to our custom fork and disable Jetifier #8666
- Add FAQ entry to the template checklists #8822
- Update Gradle to 7.5.1 #8751
- Remove extra whitespace from issue and PR templates #8755 
- Clarify that span shouldn't be in translated READMEs #8754
- Keep strong references to Picasso notification icon loading targets #8677 
- Create media session UI and fix player notification #8678
</details>

**Comment by ktprograms** [comment]
Not a regression, but the long press hint for the "Show future videos" button in the subscription feed doesn't change to indicate whether the left-pointing or right-pointing icon is show/don't show.

**Comment by Jirafey** [comment]
This version fixed my problem with current NewPipe release, which does not let me watch any videos they just load infinitely.

**Comment by Stypox** [comment]
@Jirafey just download 0.23.3, that problem was already fixed in that version

**Comment by Stypox** [comment]
Somebody reported [on reddit](https://teddit.net/r/NewPipe/comments/wz3rqw/release_candidate_v0240/im1j4wf/) that still sometimes the wrong notification thumbnail is shown when switching videos. After some testing it seems like this is reproducible only on Android 13 (and maybe 12). Here are the full reproduction steps:
- search for "playlist", while filtering only for playlists
- open a playlist having as *first two* items two videos **you have NEVER seen before** (to make sure video thumbnails are not cached)
- tap on the "Background" button in the playlist header
- from the notification, press next

=> The second video will start playing, but the shown thumbnail will be that of the first video. The strange thing is that the color of the thumbnail actually adapts to the thumbnail of the second video, which implies the OS must receive the correct thumbnail somewhere, since it's up to the OS to decide the notification color. I could also confirm that the correct thumbnail is set in the media session by using https://github.com/googlesamples/android-media-controller/. I will investigate a little more and give updates here.

**Comment by opusforlife2** [comment]
Android 12 (CalyxOS): The thumbnail gets updated correctly.

**Comment by eladkarako** [comment]
still has throttling with this and 0.23.3 for some reason.  
25kbps top..  
:..(

**Comment by AudricV** [comment]
> still has throttling with this and 0.23.3 for some reason.

On playback, on download, on all formats? Could you explain your issue a bit, please?

Also it seems you blocked all the TeamNewPipe organization members since a while.

**Comment by njmdietrich** [comment]
> still has throttling with this and 0.23.3 for some reason. 25kbps top.. :..(

Is this the same issue as #8906?

**Comment by SameenAhnaf** [comment]
Tapping on either `Remove watched` or `Show future videos` icon always show **New feed items** toast if a livestream is going on. 


https://user-images.githubusercontent.com/79245641/187223573-e12a584a-72ef-471c-b5f5-971107024f9b.mp4

**Comment by Stypox** [comment]
@SameenAhnaf I think that bug is present also in 0.23.3, so it's not a regression, though I agree it looks strange

**Comment by SameenAhnaf** [comment]
The `Show future videos` icon behavior is not present in 0.23.3 though. At least, that should be solved.

**Comment by SC1040-TS2** [comment]
> > still has throttling with this and 0.23.3 for some reason.
> 
> On playback, on download, on all formats? Could you explain your issue a bit, please?
> 
> Also it seems you blocked all the TeamNewPipe organization members since a while.
> Is this the same issue as #8906?

Close, but not quite.

The WebM video format appears to experience the throttling issue during playback, and even then only with certain channels and videos. Not sure if the MP4 format playback can replicate it so easily.

Sometimes power cycling home networking equipment solves the issue, but not for long and not with every video example.

Cloudflare 1.1.1.1 and corresponding IPv6 addresses are being used in the router settings, and DNS-over-TLS is not being used/does not affect this problem. Will test with ISP DNS addresses later.

Using mobile data can handle the affected video format more easily, somehow.

**Comment by SC1040-TS2** [comment]
Small update on my prior comment. Removing the 2 secondary RF antennae on my NETGEAR XR500 router (it comes with 4) appears to have solved the issue for Youtube-encoded WebM video playback.

The strange thing is why this worked, when other apps seemed to maintain typical connectivity with all 4 antennae connected. Maybe they were interfering with each other?

**Comment by Elmo2218** [comment]
Now im sad since im using an android kitkak phone. What to do now.

**Comment by SC1040-TS2** [comment]
> Now im sad since im using an android kitkak phone. What to do now.

How long have you used this phone for?

**Comment by Locorock** [comment]
Thumbnails in the feed tab are incorrectly resized, this only happens in the feed tab.

![Screenshot_2022-09-05-10-35-03-66_6497fb3ae9f5f2799f187f75bac0fe78](https://user-images.githubusercontent.com/6536547/188406254-88822b49-cf6d-4b7c-984e-9c12a0b470ea.jpg)

Opening a video updates the thumbnail correctly:

![Screenshot_2022-09-05-10-38-29-25_6497fb3ae9f5f2799f187f75bac0fe78](https://user-images.githubusercontent.com/6536547/188406750-75107ae6-3c65-412e-b804-6bf0f19555cd.jpg)

Thumbnails in channel and trending tabs are resized correctly:

![Screenshot_2022-09-05-10-34-13-05_6497fb3ae9f5f2799f187f75bac0fe78](https://user-images.githubusercontent.com/6536547/188406777-96cc3d86-62e4-42ae-ba39-a44b43c17aae.jpg)

**Comment by opusforlife2** [comment]
> Thumbnails in the feed tab are incorrectly resized, this only happens in the feed tab.

Strange. They show fine on Android 12 Calyx.

**Comment by Locorock** [comment]
> 

Yeah i've been trying out a few things and it seems like the problem only appears after importing both database and configs from my 0.23.1 instance of newpipe

**Comment by Stypox** [comment]
I can confirm, using fast feed. This is not a problem in the UI, but rather in the extractor, since it seems to provide thumbnails with black bars at the top and at the bottom. It should be solvable easily, I think.

**Comment by Pentaphon** [comment]
No more RCs for this one?

**Comment by swarup13** [comment]
Please release this version, it's working fine on my device.

**Comment by Stypox** [comment]
@Locorock could you test the apk provided in https://github.com/TeamNewPipe/NewPipeExtractor/pull/927? It should fix the thumbnail issue in the feed

**Comment by Stypox** [comment]
@SameenAhnaf regarding https://github.com/TeamNewPipe/NewPipe/issues/8890#issuecomment-1230466338, I tried to implement it but unfortunately it is not a good solution. The button in the top bar is actually a checkbox, so showing "hide future videos" when the button is checked and showing "show future videos" when the button is unchecked is not standard behavior. So I think we will not change this, and at least not during the release process.
![image](https://user-images.githubusercontent.com/36421898/189867262-f53b645f-a35b-4f1a-8c7d-f1df2a98a983.png)

**Comment by ktprograms** [comment]
Can't the hint be changed independently of the item text?

**Comment by Locorock** [comment]
> @Locorock could you test the apk provided in [TeamNewPipe/NewPipeExtractor#927](https://github.com/TeamNewPipe/NewPipeExtractor/pull/927)? It should fix the thumbnail issue in the feed

Yep, all thumbnails are full size now

**Comment by Locorock** [comment]
## Exception
* __User Action:__ load image
* __Request:__ https://i.ytimg.com/vi_webp/leoz6wB5dmE/maxresdefault.webp
* __Content Country:__ 
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 404
	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

```
</details>
<hr>
Honestly no idea about what is going on, but this showed upon opening a video with the wrong thumbnail

**Comment by Locorock** [comment]
![Screenshot_2022-09-13-12-07-57-31_6ad24ba22a3388112ec0c779a3703e96](https://user-images.githubusercontent.com/6536547/189874503-a3e31bb1-77ca-4b2b-9974-0564665fd8b6.jpg)
And now this

**Comment by Stypox** [comment]
@Locorock thank you for testing. Let's try with another method. I updated the APK in https://github.com/TeamNewPipe/NewPipeExtractor/pull/927, please check if this one works ;-)

@ktprograms you are right, I'm stupid :joy:, I opened #8966 which should add tooltips.

**Comment by Locorock** [comment]
┬───
│ GC Root: System class
│
├─ com.mediatek.boostfwk.identify.scroll.ScrollDispatcher class
│    Leaking: NO (a class is never leaking)
│    ↓ static ScrollDispatcher.sScrollScenario
│                              ~~~~~~~~~~~~~~~
├─ com.mediatek.boostfwk.identify.scroll.ScrollIdentify instance
│    Leaking: UNKNOWN
│    Retaining 255033 bytes in 4527 objects
│    mContext instance of org.schabi.newpipe.error.ErrorActivity with
│    mDestroyed = true
│    ↓ ScrollIdentify.mContext
│                     ~~~~~~~~
╰→ org.schabi.newpipe.error.ErrorActivity instance
​     Leaking: YES (ObjectWatcher was watching this because org.schabi.newpipe.
​     error.ErrorActivity received Activity#onDestroy() callback and
​     Activity#mDestroyed is true)
​     Retaining 254779 bytes in 4520 objects
​     key = 1d122c38-b757-4e2b-8f6e-568f07a01230
​     watchDurationMillis = 10165
​     retainedDurationMillis = 155
​     mApplication instance of org.schabi.newpipe.DebugApp
​     mBase instance of androidx.appcompat.view.ContextThemeWrapper, not
​     wrapping known Android context

METADATA

Build.VERSION.SDK_INT: 31
Build.MANUFACTURER: OnePlus
LeakCanary version: 2.5
App process name: org.schabi.newpipe.debug.release0240
Stats: LruCache[maxSize=3000,hits=1248,misses=154217,hitRate=0%]
RandomAccess[bytes=7282077,reads=154217,travel=111375804850,range=45919168,size=
56720354]
Analysis duration: 7212 ms
Also got this heap dump from the crash

**Comment by Stypox** [comment]
Uhm, that's a different issue and has nothing to do with thumbnails. Try to import an old database (i.e. where the feed has not been updated in a while), reload the feed and see if the new videos's thumbnails load correctly (the thumbnails of videos that were already in the feed before reloading won't change).

**Comment by Locorock** [comment]
> 

Yeah, seems to be working fine for the new videos

**Comment by Stypox** [comment]
Thank you again for testing. Now that the issue is solved I compressed some of your comments into single comments so that they are not "in mezzo" ;-)

**Comment by Stypox** [comment]
@AudricV and others: please check if #8972 fixes the various issues with the search suggestions list

**Comment by Stypox** [comment]
The following PRs were merged, so I updated the release candidate APKs. Please do one last test, then we can release :-)
- https://github.com/TeamNewPipe/NewPipe/pull/8899
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/920
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/925
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/926
- https://github.com/TeamNewPipe/NewPipeExtractor/pull/927
- https://github.com/TeamNewPipe/NewPipe/pull/8966
- https://github.com/TeamNewPipe/NewPipe/pull/8972

**Comment by ktprograms** [comment]
The Show/Hide future items long-press tooltip still doesn't change.

**Comment by Stypox** [comment]
As explained in the PR, Android behaves in a buggy way, but if you switch tab and go back to that tab the label will be the correct one

**Comment by ktprograms** [comment]
Even when I go out and back in, or even close (and kill from the switcher) the app, it doesn't change.

**Comment by Stypox** [comment]
Wooops you are right ;-)
I pushed a commit directly to the `release-0.24.0` branch. I made a silly copy-paste mistake. See the RC3 apk.

**Comment by xz-dev** [comment]
> Small update on my prior comment. Removing the 2 secondary RF antennae on my NETGEAR XR500 router (it comes with 4) appears to have solved the issue for Youtube-encoded WebM video playback.
> 
> The strange thing is why this worked, when other apps seemed to maintain typical connectivity with all 4 antennae connected. Maybe they were interfering with each other?

I guess it's about network speed, more antennae faster speed.

**Comment by SC1040-TS2** [comment]
Managed to get all 4 Wi-Fi antennas working again with minimal issue now.
something weird was going on at the time.

A different, though potentially related networking overhead source was
found in a specific setting within the app.

Under Settings, Appearance, Player Notification, having the *Colorize
Notification* setting turned On, even on a supported device such as a
Samsung Galaxy S9, is apparently a very intensive or janky app function, to
the point where the app destabilizes with it on.

Turning it Off seemed to reduce the chance of a failure to parse and load
Like counts, may have improved video playback consistency, and a DNS
benchmarking tool reported generally lower latencies across the board with
the function disabled. It is strange, but it could not be replicated with
disabling the player notification's thumbnail preview showing as well,
seemingly isolating it to that function being a source of general app
instability.

Odd.

**Comment by anoraktrend** [comment]
Crashes when too many downloads are going at once. (More than 10.)

**Comment by opusforlife2** [comment]
@anoraktrend No crash on 0.23.3 with so many downloads?

**Comment by Pentaphon** [comment]
> Crashes when too many downloads are going at once. (More than 10.)

That probably depends on your phone specs. Who downloads 10 videos at a time?

**Comment by n-buna404** [comment]
Newpipe by default enable limit download queue, if it happens with it enabled that is something to be investigated. If not that just the hardware being pushed to limit
