### ISSUE TITLE
NewPipe Upstream Repository is deleted from F-Droid when updating to F-Droid 1.6-Alpha0.

### ISSUE THREAD

**Issue by SC1040-TS2** [TeamNewPipe/NewPipe#9517]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Update F-Droid to 1.6-alpha0, which contains a new indexing system and massive code refactorings.
2. Notice that NewPipe is now listed as having no versions with compatible signature for a NewPipe Upstream Repo installation.
3. Check the Repositories section of F-Droid to find that the NewPipe Upstream Repo is missing.
4. Manually add it back in using Method 2 to fix.

### Expected behavior

Retention of the NewPipe Upstream Repo, but this was unexpected.

### Actual behavior

Removal of the repository occurred, requiring the end user to manually re-add it.

### Affected Android/Custom ROM version

Android 10.

### Affected device model

Samsung Galaxy S9.

### Additional information

This is not so much a Bug report as it is an advisory about an upcoming event that will affect all users should it occur in F-Droid's stable release version. Best be ready for it.

Also, the update checks of the repository having failed previously or not always worked with prior F-Droid versions may have been to blame for other app network functions hanging, especially on Wi-Fi.

**Comment by opusforlife2** [comment]
Has this been reported to F-Droid?

**Comment by SC1040-TS2** [comment]
No, not at this time, admittedly.

**Comment by opusforlife2** [comment]
Rusty search skills? :P

https://gitlab.com/fdroid/fdroidclient/-/issues/2485

**Comment by licaon-kter** [comment]
Already fixed in later F-Droid Client alphas, you can close this.
