### ISSUE TITLE
Card mode when showing channel list item search results

### ISSUE THREAD

**Issue by mahendranv** [TeamNewPipe/NewPipe#9703]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description
In search results, show channel card while Card mode is selected. Mock below.

Follow-up for the comment https://github.com/TeamNewPipe/NewPipe/pull/9310#issuecomment-1382733611

![image](https://user-images.githubusercontent.com/6584143/213371808-c2d92000-acac-479d-bded-7d678d962514.png)

### Why do you want this feature?

Card view mode is the best candidate to display information displayed in the above mock compared to list and grid modes. A channel card shall have larger thumbnail and upto 8 lines of description.

**Comment by mahendranv** [comment]
@SameenAhnaf  - Please check the mocks
1. Description tends to expand the card. Should we cap the number of lines?
2. How about bold the subscriber count to differentiate from description?

| No Limit  | 5 Lines max  |
|---|---|
|  ![image](https://user-images.githubusercontent.com/6584143/213397817-fe7eca58-b812-44f0-b5b1-1a0f0a69f501.png) | ![image](https://user-images.githubusercontent.com/6584143/213398516-ac428719-d3c6-4780-a584-ad6318c28754.png) |

Bold subscriber count variants
|  Normal  | Bold title / subs count  |
|---|---|
| ![image](https://user-images.githubusercontent.com/6584143/213399827-475e6762-8d17-4b48-ad5d-13a1d592e528.png) | ![image](https://user-images.githubusercontent.com/6584143/213399336-014805c7-2d9f-4c6e-a3e6-7c79bc4d0235.png) |

**Comment by mahendranv** [comment]
@Stypox tagging for visibility ^

Fine tuning the UI before raising PR

**Comment by mahendranv** [comment]
Got it.. Let's restrict the changes to search results. In subscription screen, list UI itself looks good.

I'll update the issue description

**Comment by Stypox** [comment]
No need to restrict. E.g. trending channels in MediaCCC should be viewable in full. Just don't implement the description for the _mini_ variant of channel items, which is the one used in the subscriptions screen.

Don't make the subscribers bold, that's unrelated to this issue and would look inconsistent.

**Comment by Stypox** [comment]
> Long channel name could be shown in marquee style.

As I said, this is not related to this PR

> Should we use List or Grid view for subscriptions?

Wdym? List & grid in the mini format are already both being used in the Subscriptions page. Card view is not used there.

> Also, history is too hard to browse on card view as mahendranv initially suggested.

As I said in the other issue, maybe some user would disagree, so we can't choose to block card mode in history. It's not like we are imposing card view to everyone: if a user likes card view (including in history), he will use it, otherwise he won't. We would need #3522 as you said.

**Comment by Stypox** [comment]
I don't really understand what your first screenshot is about. Why is the font so strange? Also it is not similar to @mahendranv's proposal, since the position of the title and the subscribers count is changed. So it really confuses me.

I agree that the channel title should be shown fully when in card view. And I also agree that in the subscriptions screen the mode should be grid when in card mode.

**Comment by mahendranv** [comment]
@SameenAhnaf this is my understanding.

Proposal is to place Channel title and sub count below the channel logo. This will leave some more space for the channel description. And the font is, you randomly picked while creating mock.

**TODO**
- [ ] In subscription screen use Grid ui when card selected
- [ ] Given card mode selected, card channel will be used in places where mini variant is not used

**Comment by Stypox** [comment]
Let's see how that works out, but I doubt there will be enough space for long channel names. Maybe instead putting video count and subscriber count below the image would be better?

**Comment by mahendranv** [comment]
Placing title and sub count below thumbnail cuts off in most cases. I see the marquee does not work when placed inside recycler view (will investigate further if it can help). Current thumbnail size is 92dp which is not enough width for title / sub count label.

In sub count label, if the count is three letters (21M) it shows properly. But same won't work for 4+ letters (5.9M).

<details>
  <summary>Screenshots</summary>

| Img1  | Img2  |
|---|---|
| ![image](https://user-images.githubusercontent.com/6584143/213915776-63170fbf-d999-4f2f-9881-0ce209713108.png) | ![image](https://user-images.githubusercontent.com/6584143/213916064-706e7ce0-b62e-46a3-91dc-ddd1ac8d55f8.png) |
  
</details>

**Comment by mahendranv** [comment]
@Stypox @SameenAhnaf 

[Here](https://github.com/TeamNewPipe/NewPipe/files/10474431/Channel_cards.zip) is the sample APK for testing. Till we fix on UI, I'll keep the card mode enabled in subscriptions tab. It can be enabled by Appearance -> List View mode -> Card.

**Comment by Stypox** [comment]
- I'd move the channel name to the right to have more space.
- Maybe making the thumbnail some dps larger would help with subs&video count lines.
- There is a way to make text ellipsized for sure, have you used both singleLine=true and ellipsize=end?

**Comment by mahendranv** [comment]
@Stypox 

>There is a way to make text ellipsized for sure, have you used both singleLine=true and ellipsize=end?
I was trying to place marquee as @SameenAhnaf mentioned. But seems like there are issues when used with RecyclerView/ConstraintLayout.

I have increased the thumbnail size to 100 dp and moved title to right. Also set number of lines to 2 for additional details. When setting ellipsis end, it tends to allocate space for `...` and cut off the text even though it is possible to display it. Another way is to use icons for sub count and number of videos. 

<details><summary>Screens</summary>

|  shot1 | shot2 |
|---|---|
|<img alt="image" src ="https://user-images.githubusercontent.com/6584143/213981427-d104468a-d568-4650-8c1c-b622ae4072ab.png" width=277/> | <img alt="image" src ="https://user-images.githubusercontent.com/6584143/213981827-eb6d4cab-f5da-434e-a519-0272cee5bc1d.png" width=277/>|
</details>

**Comment by mahendranv** [comment]
@Stypox In search screen, for channels we get only 3 lines of description. I guess extractor itself doesn't get full description.

![image](https://user-images.githubusercontent.com/6584143/214085995-0a4a8619-2ad6-4e49-8036-1d0e09a1e5a3.png)


Channel card in search screen
![image](https://user-images.githubusercontent.com/6584143/214086386-8af800d8-2aed-4519-a48e-8656e4ba0625.png)

I made sure it is the data and not due to max lines set here: https://github.com/TeamNewPipe/NewPipe/pull/9555/files#diff-30ce5c48f6146c2b1a4aabc1addb0d7384e13fc9b39b73c16254f96dcfff70b6R80

If it is limitation on extractor end, card layout won't look much different from list one.

**Comment by saeedbaloch** [comment]
```
```
سعید 
```
```

**Comment by mahendranv** [comment]
@saeedbaloch  - what's this comment?

**Comment by Stypox** [comment]
The last screenshots you have provided look good. Feel free to open a PR and we'll discuss more specific design nitpicks there. Thank you!
